### ISSUE TITLE
API Url Examples

### ISSUE THREAD

**Issue by Moon-developer** [apogiatzis/restful-user-api-django-drf#1]
Hey, love this project followed it step by step and I learnt a lot. Was just wondering if maybe you could make a README.md that details the API examples using curl to create/remove users and so on. Just thought it would be a nice feature if you had a bit of time on your hand :)

**Comment by apogiatzis** [comment]
This is a really cool suggestion tbh thanks for the feedback! :) I will try to make it happen as soon as I find some free time. In the meantime if you feel like it any pull requests are welcomed :D

**Comment by Moon-developer** [comment]
I don't mind putting something simple together 💯
